services:
  - docker:dind

variables:
  GITHUB_REF: $CI_COMMIT_SHA
  DH_IMAGE: tokend/web-client

stages:
  - build
  - publish

build:
  image: registry.gitlab.com/tokend/deployment/docker-build:latest
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - tokend
  script:
    - ci-little-helper set-pending build
    - .ci/build.sh && STATE=0 || STATE=1
    - ci-little-helper set-state $STATE build && exit $STATE

lint:
  image: registry.gitlab.com/tokend/deployment/js-build:latest
  stage: build
  tags:
    - tokend
  script:
    - ci-little-helper set-pending lint
    - .ci/lint.sh && STATE=0 || STATE=1
    - ci-little-helper set-state $STATE lint && exit $STATE

unit_test:
  image: registry.gitlab.com/tokend/deployment/js-build:latest
  stage: build
  tags:
    - tokend
  script:
    - ci-little-helper set-pending unit_test
    - .ci/test.sh && STATE=0 || STATE=1
    - ci-little-helper set-state $STATE unit_test && exit $STATE

publish dockerhub:                                                                                                                                                                                                 
  image: registry.gitlab.com/tokend/deployment/docker-build:latest
  stage: publish
  tags:
    - tokend
  only:
    - /^.+\..+\..+$/
  script:
    - ci-little-helper set-pending publish
    - .ci/publish.sh && STATE=0 || STATE=1
    - ci-little-helper set-state $STATE publish && exit $STATE
